name:                hax
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- parsec
- containers
- orthotope
- pretty
- mtl
- transformers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-name-shadowing

library:
  source-dirs: .

executables:
  hax-exe:
    main:                demo.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hax
